
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: industrial-automation-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - industrial-automation-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: industrial-automation-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IndustrialAutomationDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
      - redis
    networks:
      - industrial-automation-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: industrial-automation-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - industrial-automation-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: industrial-automation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - industrial-automation-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  sqlserver_data:
  redis_data:

networks:
  industrial-automation-network:
    driver: bridge
