apiVersion: apps/v1
kind: Deployment
metadata:
  name: industrial-automation-backend
  namespace: industrial-automation
  labels:
    app: industrial-automation-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: industrial-automation-backend
  template:
    metadata:
      labels:
        app: industrial-automation-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-org/industrial-automation-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: connection-string
        - name: JWT__Secret
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: OpenAI__ApiKey
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: industrial-automation-backend-service
  namespace: industrial-automation
  labels:
    app: industrial-automation-backend
spec:
  selector:
    app: industrial-automation-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: industrial-automation-backend-hpa
  namespace: industrial-automation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: industrial-automation-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
